version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: reloj-checador-db
    restart: unless-stopped
    environment:
      TZ: America/Mexico_City
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./backend/db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    networks:
      - reloj-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: reloj-checador-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: America/Mexico_City
      PGTZ: America/Mexico_City
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - postgres
    networks:
      - reloj-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: reloj-checador-frontend
    restart: unless-stopped
    ports:
      # Conectamos el puerto 5173 (donde Nginx lo busca) al 80 (donde vive el build de React)
      - "5173:80"
    depends_on:
      - backend
    networks:
      - reloj-network

volumes:
  postgres_data:

networks:
  reloj-network:
    driver: bridge