name: Desplegar Proyecto en Servidor

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Descargar código del repositorio
      uses: actions/checkout@v3

    - name: 2. Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: 3. Construir el Frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: 4. Subir Backend al Servidor
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "backend/"
        target: "/var/www/reloj-checador-a"
        overwrite: true

    - name: 5. Preparar carpeta remota para el Frontend
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Creando carpeta dist con permisos correctos..."
          sudo mkdir -p /var/www/reloj-checador-a/dist
          sudo chown -R $USER:$USER /var/www/reloj-checador-a
          sudo chmod -R 755 /var/www/reloj-checador-a
          rm -rf /var/www/reloj-checador-a/dist/*
          echo "Carpeta dist lista para recibir archivos."

    - name: 6. Subir nueva carpeta 'dist'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "frontend/dist/*"
        target: "/var/www/reloj-checador-a/dist"
        overwrite: true

    - name: 7. Reiniciar la aplicación en el servidor
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/reloj-checador-a/backend
          npm install --production
          pm2 restart api-checador || pm2 start index.js --name api-checador
          sudo systemctl restart nginx
          echo "✅ Despliegue completado correctamente."
